#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload
cd ~/.config/herbstluftwm
#xsetroot -solid '#AA7733'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
Alt=Mod1

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Alt-F4 close
hc keybind $Mod-t spawn xfce4-terminal
hc keybind $Mod-h spawn thunar
hc keybind $Mod-f spawn xfce4-terminal -T ranger --command=ranger
hc keybind $Mod-c spawn google-chrome-stable
hc keybind $Mod-e spawn emacs
hc keybind $Mod-$Alt-space spawn /usr/local/bin/rofi-dmenu
hc keybind Control-$Alt-Delete spawn /usr/local/bin/screenlock
hc keybind Shift-Left spawn bash ~/.config/herbstluftwm/fullscreen-defullscreen.sh
hc keybind XF86MonBrightnessUp spawn ~/Documents/Shell/backlightshortcutup.sh
hc keybind XF86MonBrightnessDown spawn ~/Documents/Shell/backlightshortcutdown.sh
hc keybind $Mod-Shift-f spawn ~/.config/herbstluftwm/toggle_frame_borders.sh
hc keybind Print spawn xfce4-screenshooter -f -s ~/Pictures/Screenshots/
hc keybind Control-Print spawn xfce4-screenshooter -w -s ~/Pictures/Screenshots/
hc keybind Shift-Print spawn xfce4-screenshooter -r -s ~/Pictures/Screenshots/
hc keybind $Mod-Shift-m spawn ~/.config/herbstluftwm/single_monitor.sh
hc keybind $Mod-Shift-b spawn ~/.config/herbstluftwm/backlight.sh
hc keybind $Mod-Shift-t spawn ~/.config/herbstluftwm/compositing.sh

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-Tab cycle_monitor
hc keybind $Mod-Shift-Tab cycle_monitor -1
hc keybind $Mod-BackSpace use_previous 
hc keybind $Mod-Shift-d spawn ~/.config/herbstluftwm/swap_monitor.py plus
hc keybind $Mod-Shift-s spawn ~/.config/herbstluftwm/swap_monitor.py minus


# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
#hc keybind $Mod-Shift-h     shift left
#hc keybind $Mod-Shift-j     shift down
#hc keybind $Mod-Shift-k     shift up
#hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-k       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( term files www im mus vid code work game misc )
tag_keys=( {1..10} 0 )

hc rename default "${tag_names[0]}" || true

for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-F$key" use_index "$i"	
        hc keybind "$Mod-Shift-F$key" spawn ~/.config/herbstluftwm/switch_and_focus.sh "$i"
    fi
done

# cycle through tags
hc keybind Control-$Alt-Right use_index +1 --skip-visible
hc keybind Control-$Alt-Left use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-Return fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-Shift-w rotate
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Alt-Tab         cycle_all +1
hc keybind $Alt-Shift-Tab   cycle_all -1
hc keybind Shift-$Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#F0F0F0'
hc set frame_bg_active_color '#FFFF00'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 1

hc attr theme.active.color '#6C4A20'
hc attr theme.normal.color '#6b6968'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 5
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule title='vlc' manage=off

# Autostart programs in specific tags or layouts
if hc silent new_attr bool my_not_first_autostart ; then
	# term:
	hc load term '(split horizontal:0.500000:1 (split vertical:0.500000:0 (clients vertical:0) (clients vertical:0)) (clients vertical:0))'
	hc spawn xfce4-terminal
	sleep 0.4
	hc cycle_frame 1
	hc spawn xfce4-terminal
	sleep 0.4
	hc cycle_frame 1
	hc spawn xfce4-terminal
fi

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# or simply:
# hc detect_monitors

# add an external panel
{
    pids=( )
    # reserve some space for the panel on monitor 0
    hc pad 0 20 "" ""
    # start the panel itself and remember its pid
    xfce4-panel -d --sm-client-disable &
    pids+=( $! )
    # or start another panel:
    # mypanel &
    # pids+=( $! )
    # wait until the panels should be stopped
    herbstclient -w '(quit_panel|reload)'
    # stopp all started panels
    kill ${pids[@]}
} &


# Monitor 2 setup
# Make sure monitor is connected
xrandr --query | grep -v eDP1 | grep "DP1 connected" || exit
hc spawn ~/.config/herbstluftwm/dual_monitor.sh
hc set_monitors 2048x1152+0+0 1600x900+2048+0 
hc pad 0 0 "" ""
hc pad 1 20 "" ""
hc keybind $Mod-Shift-Control-m spawn ~/.config/herbstluftwm/dual_monitor.sh

# xrandr --query | grep "HDMI2 connected"|| exit
# hc spawn ~/.config/herbstluftwm/triple_monitor.sh
# hc set_monitors 1920x1080+0+0 1600x900+1920+0 1280x1024+3520+0 
# hc keybind $Mod-Shift-Control-m spawn ~/.config/herbstluftwm/triple_monitor.sh

